import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import NavBar from '../components/navbar';
import Sidebar from '@/components/sidebar';
import Provider from '@/context/providers';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='h-full m-0'>
      <body className={roboto.className + 'min-h-screen bg-slate-950'}>
        <Provider>
          <div className='flex'>
            <div className=''>
            <Sidebar />
            </div>
            
            <div className='flex flex-col w-full'>
              <header className='sticky top-0 z-10'>
                <NavBar />
              </header>
              <div className=''>
              <main className=' text-white'>
                {children}
              </main>
              </div>
              
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
