import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import NavBar from '../components/navbar';
import Sidebar from '@/components/sidebar';
import Provider from '@/context/providers';

const roboto = Roboto({
  weight: '400',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en' className='h-full m-0'>
      <body className={roboto.className + 'h-full overflow-hidden'}>
        <Provider>
          <div className='static md:flex flex-row'>
            <Sidebar />
            <div className='flex flex-col flex-auto '>
              <header className=''>
                <NavBar />
              </header>
              <div className='overflow-y-auto h-screen'>
                <main className='bg-black text-white '>{children}</main>
              </div>
            </div>
          </div>
        </Provider>
      </body>
    </html>
  );
}
