import type { Metadata } from 'next'
import { Inter, Roboto } from 'next/font/google'
import './globals.css'
import { Box, Container } from '@mui/material'
import ThemeRegistry from '@/components/theme/themeRegistry'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeRegistry>
      <body>
          <Box>

          </Box>
          <Box>
            <header></header>
            <Container>
                {children}
            </Container>
          </Box>
      </body>
      </ThemeRegistry>
      
    </html>
  )
}
