import type { Metadata } from 'next'
import './globals.css'
import { Box, Container } from '@mui/material'
import ThemeRegistry from '@/components/theme/themeRegistry'
import Navbar from '@/components/navbar'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <ThemeRegistry>
      <body>
          <Box>

          </Box>
          <Box>
            <header>
              <Navbar></Navbar>
            </header>
            <Container>
                {children}
            </Container>
          </Box>
      </body>
      </ThemeRegistry>
      
    </html>
  )
}
